[package]
name = "pincerpdf-desktop-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
serde = { version = "=1.0.229", features = ["derive"] }

[lints]
workspace = true
