[package]
name = "pincerpdf-merge"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
pincerpdf-application = { path = "../pincerpdf-application" }
pincerpdf-domain = { path = "../pincerpdf-domain" }
pincerpdf-engine-api = { path = "../pincerpdf-engine-api" }
pincerpdf-filesystem = { path = "../pincerpdf-filesystem" }

[lints]
workspace = true
