[package]
name = "pincerpdf-application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
pincerpdf-domain = { path = "../pincerpdf-domain" }
pincerpdf-engine-api = { path = "../pincerpdf-engine-api" }

[lints]
workspace = true
